{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-lb-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    cf-lb-component: controller
{{- end }}
